cd ~/projects/go-k8s-demo

cat > .github/workflows/ci.yml <<'EOF'
name: Go CI

"on":
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: syslians/go-k8s-demo

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Test
        run: go test ./...

      - name: Build Go
        run: go build ./cmd/server

      - name: Login to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/syslians/go-k8s-demo:${{ github.sha }}
            ghcr.io/syslians/go-k8s-demo:latest
EOF
